### ISSUE TITLE
Container qui ne contient rien ?

### ISSUE THREAD

**Issue by Kae-Tempest** [Les-Moddeurs-Francais/Container-Tutorial#1]
Quand on laisse des blocs dedans ils disparaisse a la réouverture, un container est censé contenir des choses non ?

**Comment by Mysterious-Dev** [comment]
> Quand on laisse des blocs dedans ils disparaisse a la réouverture, un container est censé contenir des choses non ?

Non ça c'est une tile entity, on container c'est une interface accueillant des slots...
